import { HelpDeskRequest } from "./types";

export const MOCK_REQUESTS: HelpDeskRequest[] = [
  {
    id: "1",
    reference: "REQ-2026-001",
    subject: "Problème d'accès VPN",
    description: "Impossible de me connecter au VPN depuis ce matin.",
    category: "IT",
    priority: "Élevée",
    status: "En Cours",
    service: "Support IT",
    userId: "user_1",
    userName: "Ahmed Mansour",
    createdAt: "2026-06-08T09:00:00Z",
    updatedAt: "2026-06-08T10:30:00Z",
  },
  {
    id: "2",
    reference: "REQ-2026-002",
    subject: "Demande de nouveau badge",
    description: "Mon badge actuel est endommagé.",
    category: "Sécurité",
    priority: "Normale",
    status: "Ouverte",
    service: "Service Sécurité",
    userId: "user_1",
    userName: "Ahmed Mansour",
    createdAt: "2026-06-09T08:15:00Z",
    updatedAt: "2026-06-09T08:15:00Z",
  },
  {
    id: "3",
    reference: "REQ-2026-003",
    subject: "Renouvellement contrat mutuelle",
    description: "Besoin des documents pour le renouvellement.",
    category: "RH",
    priority: "Faible",
    status: "Résolue",
    service: "Ressources Humaines",
    userId: "user_2",
    userName: "Sara El Amrani",
    createdAt: "2026-06-07T14:20:00Z",
    updatedAt: "2026-06-08T16:00:00Z",
  },
  {
    id: "4",
    reference: "REQ-2026-004",
    subject: "Panne climatisation Bureau 402",
    description: "La clim ne refroidit plus dans le bureau 402.",
    category: "Chantier",
    priority: "Critique",
    status: "Ouverte",
    service: "Maintenance",
    userId: "user_3",
    userName: "Karim Bennani",
    createdAt: "2026-06-09T10:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
  },
];
